language: python
dist: bionic

python:
  - "3.6"
  - "3.7"

install:
  - curl -sSf https://build.travis-ci.com/files/rustup-init.sh | sh -s -- -y --default-toolchain nightly-2019-07-19-x86_64-unknown-linux-gnu --profile=minimal
  - export PATH=${TRAVIS_HOME}/.cargo/bin:$PATH
  - rustup component add clippy --toolchain nightly-2019-07-19-x86_64-unknown-linux-gnu
  - rustup component add rustfmt --toolchain nightly-2019-07-19-x86_64-unknown-linux-gnu
  - pip install pylint yapf setuptools_rust
  - python setup.py develop

script:
  - cargo fmt --all -- --check
  - cargo clippy -- -D warnings
  - pytest
  - yapf ffp -r --diff
  - pylint ffp
